### ISSUE TITLE
Failed to connect testing javascript course with dicord

### ISSUE THREAD

**Issue by harshkc** [kentcdodds/js-testing-fundamentals#14]
I tried connecting the Testing JavaScript Course account to discord but it fails to do so.
Here is the error it shows:
`{"errorType":"object","errorMessage":"[object Object]","trace":[]}`

**Comment by kentcdodds** [comment]
Rats. Could you try again? Sometimes that can be finicky...

**Comment by harshkc** [comment]
I tried yesterday and today 4 times today on chrome, failed to connect.
Tried firefox first try success.
Some extensions might be messing with something.
Should I close this Issue or will you?

**Comment by kentcdodds** [comment]
My guess is it's extensions. Glad it worked for you :) Cheers!
